diff --git a/features/support/env.rb b/features/support/env.rb
index 64ddf61..ec6ae21 100644
--- a/features/support/env.rb
+++ b/features/support/env.rb
@@ -1,3 +1,4 @@
+require "simplecov"
 # IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
 # It is recommended to regenerate this file in the future when you upgrade to a
 # newer version of cucumber-rails. Consider adding your own code to a new file
@@ -55,4 +56,3 @@ end
 # The :transaction strategy is faster, but might give you threading problems.
 # See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
 Cucumber::Rails::Database.javascript_strategy = :truncation
-
