require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  NewCops: enable
  TargetRubyVersion: 3.1

Bundler/GemVersion:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SingleLineBlockChain:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/NumberConversion:
  AutoCorrect: false
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitBlockExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/ClassMethodsDefinitions:
  EnforcedStyle: self_class

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MissingElse:
  EnforcedStyle: case

Style/RescueModifier:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

inherit_from: .rubocop_todo.yml
