diff --git a/Gemfile b/Gemfile
index 6b34535..1a984ec 100644
--- a/Gemfile
+++ b/Gemfile
@@ -46,7 +46,7 @@ gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
 gem "bootsnap", require: false
 
 # Use Sass to process CSS
-# gem "sassc-rails"
+gem 'sassc-rails'
 
 # Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
 # gem "image_processing", "~> 1.2"
@@ -73,3 +73,57 @@ group :test do
   gem "selenium-webdriver"
   gem "webdrivers"
 end
+
+group :development do
+  # Annotate models, factories, and spec with table layout
+  gem 'annotate'
+  # Add performance cops
+  gem 'rubocop-performance'
+  # Add Rails cops
+  gem 'rubocop-rails'
+  # Add Rspec cops
+  gem 'rubocop-rspec'
+  # Add slim generator
+  gem 'slim-rails'
+end
+
+group :development, :test do
+  # Help kill N+1 queries
+  gem 'bullet'
+  # For debugging
+  gem 'pry-byebug'
+  # Testing
+  gem 'rspec-rails'
+end
+
+group :test do
+  # Cucumber testing
+  gem 'cucumber-rails', require: false
+  # Empty database when needed during testing
+  gem 'database_cleaner'
+  # Factories for specs
+  gem 'factory_bot_rails'
+  # Supports save_and_open_page
+  gem 'launchy'
+  # Assigns in Rspec
+  gem 'rails-controller-testing'
+  # Mocks in Rspec
+  gem 'rspec-activemodel-mocks'
+  # Code coverage
+  gem 'simplecov', require: false
+end
+
+# Authentication
+gem 'devise'
+# Pagination
+gem 'kaminari'
+# Use initials for avatar
+gem 'letter_avatar'
+# SEO meta tags
+gem 'meta-tags', require: 'meta_tags'
+# Authorization
+gem 'pundit'
+# Search form gem
+gem 'ransack'
+# Add slim. Note the generator is in the dev group. Might save a touch on bundle size by not using slim-rails here.
+gem 'slim'
