diff --git a/Gemfile b/Gemfile
index 13ab512..2ba6bd1 100644
--- a/Gemfile
+++ b/Gemfile
@@ -52,3 +52,46 @@ end
 
 # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
 gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
+
+group :development do
+  gem "ruby-prof"
+  gem "slim-rails"
+  gem "rubocop-rails"
+  gem "annotate"
+end
+
+group :development, :test do
+  gem "rspec-rails"
+  gem "pry-byebug"
+  gem "bullet"
+end
+
+group :test do
+  gem "rspec-activemodel-mocks"
+  gem "factory_bot_rails"
+  gem "cucumber-rails", require: false
+  gem "database_cleaner"
+  gem "launchy"
+  gem "simplecov", require: false
+  gem "rails-controller-testing"
+end
+
+group :production do
+  # Heroku
+  gem "rails_12factor"
+end
+
+gem "pg"
+gem "bootstrap", "~> 4.0.0.beta2.1"
+gem "autoprefixer-rails"
+gem "devise"
+gem "pundit"
+gem "slim"
+gem "kaminari"
+gem "meta-tags", require: "meta_tags"
+gem "jquery-rails"
+gem "ransack"
+gem "letter_avatar"
+
+# Heroku
+ruby "2.4.2"
