diff --git a/Gemfile b/Gemfile
index 851a3c5..d4cac2e 100644
--- a/Gemfile
+++ b/Gemfile
@@ -5,7 +5,7 @@ gem 'rails', '3.2.12'
 # Bundle edge Rails instead:
 # gem 'rails', :git => 'git://github.com/rails/rails.git'
 
-gem 'sqlite3'
+# gem 'sqlite3'
 
 
 # Gems used only for assets and not required
@@ -15,7 +15,8 @@ group :assets do
   gem 'coffee-rails', '~> 3.2.1'
 
   # See https://github.com/sstephenson/execjs#readme for more supported runtimes
-  # gem 'therubyracer', :platforms => :ruby
+  gem 'therubyracer', :platforms => :ruby
+  gem 'less-rails'
 
   gem 'uglifier', '>= 1.0.3'
 end
@@ -36,3 +37,39 @@ gem 'jquery-rails'
 
 # To use debugger
 # gem 'debugger'
+
+group :development do
+  gem 'newrelic_rpm'
+  gem 'ruby-prof'
+  gem 'haml-rails'
+end
+
+group :development, :test do
+  gem 'sqlite3'
+  gem 'rspec-rails'
+  gem 'cucumber'
+  gem 'rb-readline'
+  gem 'debugger'
+end
+
+group :test do
+  gem 'factory_girl'
+  gem 'cucumber-rails', :require => false
+  gem 'capybara'
+  gem 'database_cleaner'
+  gem 'launchy'
+  gem 'autotest-rails'
+  gem 'simplecov', :require => false
+end
+
+group :production do
+  gem 'pg'
+end
+
+gem 'thin'
+gem 'devise'
+gem 'cancan'
+gem 'haml'
+gem 'will_paginate'
+gem 'twitter-bootstrap-rails'
+gem 'meta-tags', :require => 'meta_tags'
