diff --git a/Gemfile b/Gemfile
index 45ffe90..f1c3692 100644
--- a/Gemfile
+++ b/Gemfile
@@ -5,7 +5,7 @@ gem 'rails', '3.2.5'
 # Bundle edge Rails instead:
 # gem 'rails', :git => 'git://github.com/rails/rails.git'
 
-gem 'sqlite3'
+# gem 'sqlite3'
 
 
 # Gems used only for assets and not required
@@ -36,3 +36,36 @@ gem 'jquery-rails'
 
 # To use debugger
 # gem 'debugger'
+
+group :development do
+  gem 'newrelic_rpm'
+  gem 'ruby-prof'
+  gem 'haml-rails'
+end
+
+group :development, :test do
+  gem 'sqlite3'
+  gem 'rspec-rails'
+  gem 'cucumber'
+end
+
+group :test do
+  gem 'factory_girl'
+  gem 'cucumber-rails', :require => false
+  gem 'capybara'
+  gem 'database_cleaner'
+  gem 'launchy'
+  gem 'ruby-debug19'
+  gem 'autotest-rails'
+  gem 'simplecov', :require => false
+end
+
+group :production do
+  gem 'pg'
+end
+
+gem 'thin'
+gem 'devise'
+gem 'cancan'
+gem 'haml'
+gem 'will_paginate'
