diff --git a/Gemfile b/Gemfile
index 292c232..1148513 100644
--- a/Gemfile
+++ b/Gemfile
@@ -5,5 +5,5 @@ gem 'rails', '4.0.2'
 
 # Use sqlite3 as the database for Active Record
-gem 'sqlite3'
+gem 'sqlite3', group: [:development, :test]
 
 # Use SCSS for stylesheets
@@ -17,5 +17,7 @@ gem 'coffee-rails', '~> 4.0.0'
 
 # See https://github.com/sstephenson/execjs#readme for more supported runtimes
-# gem 'therubyracer', platforms: :ruby
+gem 'therubyracer', platforms: :ruby
+gem 'less-rails'
+gem 'twitter-bootstrap-rails'
 
 # Use jquery as the JavaScript library
@@ -37,5 +39,5 @@ end
 
 # Use unicorn as the app server
-# gem 'unicorn'
+gem 'unicorn'
 
 # Use Capistrano for deployment
@@ -43,3 +45,40 @@ end
 
 # Use debugger
-# gem 'debugger', group: [:development, :test]
+gem 'debugger', group: [:development, :test]
+
+group :development do
+  gem 'newrelic_rpm'
+  gem 'ruby-prof'
+  gem 'slim-rails'
+end
+
+group :development, :test do
+  gem 'rspec-rails'
+  gem 'cucumber'
+end
+
+group :test do
+  gem 'factory_girl'
+  gem 'cucumber-rails', :require => false
+  gem 'capybara'
+  gem 'database_cleaner'
+  gem 'launchy'
+  gem 'autotest-rails'
+  gem 'simplecov', :require => false
+end
+
+group :production do
+  gem 'pg'
+  # Heroku
+  # gem 'rails_12factor'
+end
+
+gem 'devise'
+gem 'cancan'
+gem 'haml'
+gem 'slim'
+gem 'will_paginate'
+gem 'meta-tags', :require => 'meta_tags'
+
+# Heroku
+# ruby '2.0.0'
