diff --git a/features/support/env.rb b/features/support/env.rb
index 9f3b86d..bbd395b 100644
--- a/features/support/env.rb
+++ b/features/support/env.rb
@@ -1,3 +1,5 @@
+require 'simplecov'
+ENV["RAILS_ENV"] = 'test'
 # IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
 # It is recommended to regenerate this file in the future when you upgrade to a
 # newer version of cucumber-rails. Consider adding your own code to a new file
