diff --git a/features/support/env.rb b/features/support/env.rb
index 29f204c..65ab5e9 100644
--- a/features/support/env.rb
+++ b/features/support/env.rb
@@ -1,3 +1,4 @@
+require 'simplecov'
 # IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
 # It is recommended to regenerate this file in the future when you upgrade to a 
 # newer version of cucumber-rails. Consider adding your own code to a new file 
